"""
Django settings for edr_server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-for-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

if not os.environ.get('DJANGO_SECRET_KEY') and not DEBUG:
    print("WARNING: Running in production (DEBUG=False) without DJANGO_SECRET_KEY set!")

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'health',
    'ingestion',
]


# rest framework setting and configurations that are added here 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



MIDDLEWARE = [
    'edr_server.middleware.DecompressMiddleware',  # Custom Gzip Middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edr_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edr_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Karachi'
USE_TZ = True





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication Redirects
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'  # Corrected path



from mongoengine import connect

connect(
    db='edr_telemetry',
    host='localhost',
    port=27017
)


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# celery defualt pool does not work on the windows so we added solo pool for normal working .. code changes ..

# Windows-specific fix
CELERY_TASK_ALWAYS_EAGER = False  # Keep async behavior
CELERY_WORKER_POOL = 'gevent'  # Use gevent pool for concurrency on Windows


# ========== REDIS CACHE FOR RATE LIMITING ==========
# Use Redis database 1 (separate from Celery which uses database 0)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Database 1 for caching/rate limiting
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'TIMEOUT': 60,  # Default timeout for cache keys (1 minute)
    }
}

# ========== RATE LIMITING CONFIGURATION ==========
RATELIMIT_ENABLE = True  # Set to False to disable globally (for testing)
RATELIMIT_USE_CACHE = 'default'  # Use the default cache backend defined above
RATELIMIT_FAIL_OPEN = True  # If Redis is down, allow requests (don't block EDR operations)

# Rate limit values (configurable per environment)
# These can be overridden in .env for different environments (dev/prod)
RATELIMIT_TELEMETRY = os.getenv('RATELIMIT_TELEMETRY', '1000/m')  # High volume - agent telemetry
RATELIMIT_AUTH = os.getenv('RATELIMIT_AUTH', '5/1h')  # Strict - prevent brute force
RATELIMIT_DASHBOARD_READ = os.getenv('RATELIMIT_DASHBOARD_READ', '100/m')  # Dashboard API reads
RATELIMIT_DASHBOARD_WRITE = os.getenv('RATELIMIT_DASHBOARD_WRITE', '50/m')  # Dashboard API writes
RATELIMIT_RESPONSE_ACTION = os.getenv('RATELIMIT_RESPONSE_ACTION', '20/m')  # Response actions (kill process)
RATELIMIT_ISOLATE = os.getenv('RATELIMIT_ISOLATE', '10/m')  # Critical actions (isolate host)
RATELIMIT_ADMIN = os.getenv('RATELIMIT_ADMIN', '20/m')  # Admin operations
RATELIMIT_PAGE_VIEW = os.getenv('RATELIMIT_PAGE_VIEW', '200/m')  # HTML page views



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ingestion': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Set to DEBUG for detailed logs
            'propagate': False,
        },
        'ratelimit': {
            'handlers': ['console'],
            'level': 'WARNING',  # Log rate limit violations
            'propagate': False,
        },
    },
}
