from mongoengine import Document, StringField, DictField, DateTimeField, IntField, BooleanField, FloatField
from datetime import datetime, timezone
import uuid
import secrets


# ==========================================
# ENROLLMENT & CONFIGURATION MODELS
# ==========================================

class EnrollmentToken(Document):
    """
    Secure token for agent onboarding.
    Generated by admin, used once during agent installation.
    """
    token = StringField(required=True, unique=True, default=lambda: secrets.token_hex(32))
    description = StringField(default="")
    expires_at = DateTimeField()  # Optional expiry
    max_uses = IntField(default=1)  # -1 for unlimited
    current_uses = IntField(default=0)
    is_active = BooleanField(default=True)
    created_by = StringField(required=True)  # Username of admin who created
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))
    
    meta = {
        'collection': 'enrollment_tokens',
        'indexes': ['token', 'is_active', '-created_at']
    }
    
    def is_valid(self):
        """Check if token can still be used."""
        if not self.is_active:
            return False
        if self.expires_at:
            # Handle both timezone-aware and naive datetimes
            # MongoDB may store as naive, so we make expires_at aware if needed
            expires = self.expires_at
            if expires.tzinfo is None:
                # Naive datetime - assume it's UTC
                expires = expires.replace(tzinfo=timezone.utc)
            if datetime.now(timezone.utc) > expires:
                return False
        if self.max_uses != -1 and self.current_uses >= self.max_uses:
            return False
        return True
    
    def increment_usage(self):
        """Mark one use of the token."""
        self.current_uses += 1
        self.save()
    
    def __str__(self):
        return f"{self.token[:8]}... ({self.description})"


class AgentConfig(Document):
    """
    Versioned configuration policy for agents.
    Stores module settings, telemetry intervals, exclusions etc.
    """
    config_id = StringField(required=True, unique=True, default=lambda: str(uuid.uuid4()))
    name = StringField(default="Default Policy")
    version = IntField(default=1)
    
    # The actual JSON payload sent to agents
    config_json = DictField(default=lambda: {
        "modules": {
            "file_monitor": {"enabled": True},
            "process_monitor": {"enabled": True},
            "network_monitor": {"enabled": False}
        },
        "telemetry": {
            "batch_size": 100,
            "heartbeat_interval": 30
        }
    })
    
    created_by = StringField()  # Username
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))
    
    meta = {
        'collection': 'agent_configs',
        'indexes': ['name', 'version', '-created_at']
    }
    
    def __str__(self):
        return f"{self.name} v{self.version}"


# ==========================================
# COMMAND & RESPONSE MODELS  
# ==========================================

class PendingCommand(Document):
    """
    Command queue - stores commands waiting to be executed by agents.
    This implements the "HTTP Polling" pattern where agents poll for these records.
    """
    # Unique ID for the command (UUID)
    command_id = StringField(required=True, unique=True, default=lambda: str(uuid.uuid4()))
    
    # Target endpoint identifier
    agent_id = StringField(required=True)
    
    # Command details
    command_type = StringField(required=True)  # e.g., 'kill_process', 'isolate_host'
    parameters = DictField()  # e.g., {'pid': 1234}
    
    # Status tracking
    # Options: 'new', 'in_progress', 'completed', 'failed', 'timeout'
    status = StringField(required=True, default='new')
    
    # Result from agent
    result = DictField()  # e.g., {'status': 'success', 'message': 'Process killed'}
    
    # Metadata
    issued_by = StringField(required=True)  # Analyst email/username
    related_alert_id = StringField()  # Optional link to an alert
    
    # Timestamps
    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))
    expires_at = DateTimeField()  # Auto-delete/timeout after X minutes
    completed_at = DateTimeField()
    
    meta = {
        'collection': 'pending_commands',
        'indexes': [
            'agent_id',
            'status',
            'expires_at'  # For cleanup/TTL
        ]
    }

class ResponseAction(Document):
    """
    Audit trail for all response actions taken.
    This is an append-only log for compliance and history.
    """
    action_id = StringField(required=True, unique=True, default=lambda: str(uuid.uuid4()))
    
    # Who did what
    user = StringField(required=True)  # Analyst email
    action_type = StringField(required=True)  # 'kill_process', 'isolate_host'
    target_agent = StringField(required=True)
    
    # Context
    command_id = StringField()  # Link to PendingCommand
    alert_id = StringField()
    reason = StringField()  # Why was this action taken?
    
    # Outcome
    status = StringField(default='initiated')  # 'initiated', 'success', 'failed'
    result_summary = StringField()
    
    timestamp = DateTimeField(default=lambda: datetime.now(timezone.utc))
    
    meta = {
        'collection': 'response_actions',
        'indexes': [
            '-timestamp',
            'user',
            'target_agent'
        ]
    }


class Agent(Document):
    """
    Registered agent metadata.
    Updated on every telemetry event to track agent status and version.
    """
    # Unique identifier (UUID from agent)
    agent_id = StringField(required=True, unique=True)
    
    # Display name
    hostname = StringField()
    
    # OS information
    os_version = StringField(default='unknown')  # e.g., "Windows 10", "Ubuntu 22.04"
    
    # Software version running on agent
    agent_version = StringField(default='unknown')
    
    # Status tracking
    first_seen = DateTimeField()
    last_seen = DateTimeField()
    
    # Active/deactivated status
    is_active = BooleanField(default=True)  # Can be set False to disable agent
    
    # Calculated status
    is_online = BooleanField(default=False)
    
    # Configuration version
    config_version = IntField(default=1)
    
    identity_token = StringField(unique=True, sparse=True)
    identity_token_created_at = DateTimeField()
    
    # Heartbeat metrics (Phase-1 Addition)
    cpu_percent = FloatField(default=0)
    memory_mb = IntField(default=0)
    uptime_seconds = IntField(default=0)
    events_sent = IntField(default=0)
    last_heartbeat = DateTimeField()
    
    # Configuration Management (Phase-2 Addition)
    config_id = StringField()  # Reference to AgentConfig.config_id
    enrollment_token_id = StringField()  # Reference to EnrollmentToken._id
    config_status = StringField(default='PENDING')  # SYNCED, PENDING, FAILED
    
    def regenerate_token(self):
        """Generate new identity token (for rotation or compromise)."""
        import secrets
        self.identity_token = secrets.token_hex(32)
        self.identity_token_created_at = datetime.now(timezone.utc)
        self.save()
        return self.identity_token
        
    meta = {
        'collection': 'agents',
        'indexes': [
            'agent_id',
            '-last_seen',
            'is_online',
            'config_status'
        ]
    }
    
    def __str__(self):
        return f"Agent {self.agent_id[:8]}... v{self.agent_version}"
